### PR TITLE
Readme

### PR DESCRIPTION
**Pull request by alec-hoyland**
Significant improvements to .rst version of the readme.
Updates "How Do I...?" with making custom conductances.

Still to do:
Need to delete .md version of the readme.
Need to add new .gif of puppeteer in action

### CODE REVIEW

**Comment by sg-s** [comment]
1. looks great, make a README.rst and delete the markdown file
2. master will no longer receive pull requests (master is reserved for kapalin to automatically push new commits if tests pass) -- so we should merge this into `dev`, not `master`

**Comment by alec-hoyland** [comment]
Deleted `README.md` (942dc78). The new `README.rst` is in `/docs`.

**Comment by sg-s** [comment]
no, the new readme should also be in the root, otherwise github won't show anything

**Comment by sg-s** [comment]
has been merged

**Pull request closed without merging**
