### PR TITLE
Set y-limits to minimum and maximum of the reversal potential

### PR DESCRIPTION
**Pull request by alec-hoyland**

### CODE REVIEW

**Comment by sg-s** [comment]
there's a bug here -- you should ignore the `E_Ca` because it's ludicrous. but how does one ever find the calcium channel and not the others? i think this is a lost cause -- we should abandon this unless you have a smart, simple way of fixing this

**Comment by sg-s** [comment]
god dammit -- this was merged when it shouldn't have been -- did you branch documentation from this branch, and not from master?

**Comment by alec-hoyland** [comment]
I might have fucked up -- can you revert it and I'll redo the changes in a
*correct* branch -- it's two lines of code.

**Comment by sg-s** [comment]
never mind --changes have been reverted in #109 branch because `x.manipulate` has changed

**Pull request merged**
