### PR TITLE
Add Morris-Lecar model

### PR DESCRIPTION
**Pull request by alec-hoyland**

### CODE REVIEW

**Comment by alec-hoyland** [comment]
Here is a skeleton for how arbitrary dynamical systems (such as the Morris-Lecar model) could be implemented.

**Comment by alec-hoyland** [comment]
It doesn't seem like there *is* an RK4 scheme for the `CalciumMech`

```c++
// Runge-Kutta 4 integrator
void CalciumMech::integrateMS(int k, double V, double Ca_)
{
    if (k == 4){return;}

    comp->k_Ca[k] = dt*(Cadot(Ca_));
    // mexPrintf("k_Ca[k] = %f\n", comp->k_Ca[k]);
}
```

**Comment by sg-s** [comment]
it's a it confusing -- it sets k_Ca on a per-sub-step basis in compartment. 

for reasons that are inscrutable to me right now, the rk4 integration of calcium happens in compartment. 

but the first point is far more important -- we need some demonstration of this doing something

**Comment by alec-hoyland** [comment]
I added injected current functionality to the model by directly modifying the equation of state for *v*. I also added in the capacitance (slows down oscillations). 3 nA of injected current seems to work nicely.

**Comment by sg-s** [comment]
Want to merge this @alec-hoyland

**Comment by alec-hoyland** [comment]
Let me check on this today, see if it still works.

**Comment by alec-hoyland** [comment]
Morris-Lecar model already exists in master. Closing.

**Pull request closed without merging**
