### PR TITLE
Rheobase

### PR DESCRIPTION
**Pull request by alec-hoyland**
Add function to compute the minimum current needed to produce spiking

### CODE REVIEW

**Comment by alec-hoyland** [comment]
As is clear, my subconscious prefers it as well.

**Comment by sg-s** [comment]
Also, there is an error in logic, this line:

```
  I_ext = options.current_steps(ii);
```

is never reached. right?

**Comment by sg-s** [comment]
More issues: for our bursting models, it incorrectly identifies the rheobase. You shoulds `fminbnd` to find the true rheboase

**Comment by alec-hoyland** [comment]
I was hoping to avoid doing black box optimization, but it's a single variable and shouldn't be too difficult to implement if we consider the rheobase to be the minimum current to elicit an action potential (not necessarily tonic or phasic firing).

**Pull request merged**
